services:
  dock-dploy:
    image: hhftechnology/dock-dploy:latest
    network_mode: bridge
    container_name: dock-dploy
    restart: unless-stopped
    ports:
      - 3010:3000
    environment:
      - NODE_ENV=production
