volumes:
  owncloud-db:
    driver: local
  owncloud-data:
    driver: local

services:
  mariadb:
    image: mariadb:latest
    container_name: owncloud_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
    volumes:
      - owncloud-db:/var/lib/mysql

  owncloud:
    image: owncloud/server:latest
    container_name: owncloud_server
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    environment:
      # - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_ADMIN_USERNAME=mohawkey
      - OWNCLOUD_ADMIN_PASSWORD=addict
      - OWNCLOUD_MYSQL_UTF8MB4=true
    volumes:
      - owncloud-data:/mnt/data
